%% High-Fidelity Tracking
%
% Loads point cloud data from hifi_data.mat (generated by hifi_sensor_test.m)
% and runs the drone_PHD extended target tracker with visualization.

clear; clc; close all

addpath('../../brew/')

%% Load data
load('hifi_data.mat', ...
    't_sensor', 'dt_sensor', 'N', 'points', ...
    'center', 'sensor_loc', 'sensor_dir', 'sensor_slope');

%% Setup motion model / filter
target_motion = BREW.dynamics.Integrator_3D();

H = [eye(3) zeros(3,3)];
R_noise = 0.01 * eye(3);
process_noise = 1 * eye(6);

inner_filter = BREW.filters.GGIWEKF('dyn_obj', target_motion, ...
    'H', H, 'process_noise', process_noise, 'measurement_noise', R_noise);

alpha  = {100};
beta   = {1};
m0     = {[center(1); center(2); center(3); 0; 0; 0]};
cov0   = {diag([20,20,20,2,2,2])};
IWdof  = {10};
IWshape = {eye(3)};

birth_model = BREW.distributions.GGIWMixture( ...
    'alphas', alpha, 'betas', beta, ...
    'means', m0, 'covariances', cov0, ...
    'IWdofs', IWdof, 'IWshapes', IWshape, ...
    'weights', [1]);

%% Setup sensor + tracker
sen = sensor_station('location', sensor_loc, ...
    'view_vector', sensor_dir, 'grid_slope', sensor_slope);

sen.internal_tracker = drone_PHD( ...
    'filter', copy(inner_filter), ...
    'birth_model', copy(birth_model), ...
    'prob_detection', 0.8, ...
    'prob_survive', 0.9, ...
    'max_terms', 50, ...
    'cluster_obj', BREW.clustering.DBSCAN_obj(3,5), ...
    'extract_threshold', 0.3);

%% Visualization setup
pngDir = 'hifi_png/';
if ~exist(pngDir,'dir'), mkdir(pngDir); end

gifFilename = 'HiFiDroneTracking.gif';

f = figure;
subplot(1,2,1); axis equal; view(3); hold on
subplot(1,2,2); axis equal; view(2); hold on

sc = 0.9;

%% Run tracker
for k = 1:N
    %% Predict + correct
    sen.internal_tracker.predict(dt_sensor);
    [sen.internal_tracker,trimmed_meas] = ...
        sen.internal_tracker.correct(dt_sensor, points{k}', 'basis_tracking', true);

    est_mix = sen.internal_tracker.cleanup();

    %% 3-D view
    subplot(1,2,1); cla
    scatter3(points{k}(:,1), points{k}(:,2), points{k}(:,3), 6, '*'); hold on

    for ii = 1:length(est_mix)
        p_est = est_mix.distributions{ii}.mean(1:3);
        B     = est_mix.distributions{ii}.basis;
        scale = 5;
        plot3([p_est(1) p_est(1)+scale*B(1,1)], ...
              [p_est(2) p_est(2)+scale*B(2,1)], ...
              [p_est(3) p_est(3)+scale*B(3,1)], 'r', 'LineWidth', 2);
        plot3([p_est(1) p_est(1)+scale*B(1,2)], ...
              [p_est(2) p_est(2)+scale*B(2,2)], ...
              [p_est(3) p_est(3)+scale*B(3,2)], 'g', 'LineWidth', 2);
        plot3([p_est(1) p_est(1)+scale*B(1,3)], ...
              [p_est(2) p_est(2)+scale*B(2,3)], ...
              [p_est(3) p_est(3)+scale*B(3,3)], 'b', 'LineWidth', 2);
    end

    est_mix.plot_distributions([1,2,3], 'Color', 'r', 'LineWidth', 2); hold off

    xlim(sc*[0 30]); ylim(sc*[0 30]); zlim(sc*[-15 15])

    %% 2-D top-down view
    subplot(1,2,2); cla
    scatter(points{k}(:,1), points{k}(:,2), 6, '*'); hold on
    % for ii = 1:length(trimmed_meas)
    %     scatter3(trimmed_meas{ii}(1,:), trimmed_meas{ii}(2,:), trimmed_meas{ii}(3,:), 6, '*'); hold on
    % end
    xlim(sc*[0 30]); ylim(sc*[0 30]); zlim(sc*[-15 15])

    drawnow;

    %% GIF capture
    frame = getframe(f);
    img   = frame2im(frame);
    [A, map] = rgb2ind(img, 256);

    if k == 1
        imwrite(A, map, gifFilename, 'gif', ...
                'LoopCount', Inf, 'DelayTime', 0.1);
    else
        imwrite(A, map, gifFilename, 'gif', ...
                'WriteMode', 'append', 'DelayTime', 0.1);
    end

    saveas(gcf, [pngDir, sprintf('frame_%i',k), '.png'])
end

fprintf('Saved %s  (%d frames)\n', gifFilename, N);
